In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('loan_approval_dataset.csv')
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [3]:
df.shape

(4269, 13)

In [4]:
# check for unique values n each column
df.nunique()

loan_id                      4269
 no_of_dependents               6
 education                      2
 self_employed                  2
 income_annum                  98
 loan_amount                  378
 loan_term                     10
 cibil_score                  601
 residential_assets_value     278
 commercial_assets_value      188
 luxury_assets_value          379
 bank_asset_value             146
 loan_status                    2
dtype: int64

In [5]:
# check for duplicates

df.duplicated().sum()

np.int64(0)

In [6]:
df.drop(columns=['loan_id'], inplace=True)

In [7]:
# list of columns
df.columns

Index([' no_of_dependents', ' education', ' self_employed', ' income_annum',
       ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [8]:
## remove blank space from the column names
df.columns = [c.strip() for c in df.columns]
df.columns

Index(['no_of_dependents', 'education', 'self_employed', 'income_annum',
       'loan_amount', 'loan_term', 'cibil_score', 'residential_assets_value',
       'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value',
       'loan_status'],
      dtype='object')

In [9]:
# separate dependent data from independent data
X = df.drop(columns=['loan_status'])
y = df.loan_status

In [10]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4269 entries, 0 to 4268
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   no_of_dependents          4269 non-null   int64
 1   education                 4269 non-null   object
 2   self_employed             4269 non-null   object
 3   income_annum              4269 non-null   int64
 4   loan_amount               4269 non-null   int64
 5   loan_term                 4269 non-null   int64
 6   cibil_score               4269 non-null   int64
 7   residential_assets_value  4269 non-null   int64
 8   commercial_assets_value   4269 non-null   int64
 9   luxury_assets_value       4269 non-null   int64
 10  bank_asset_value          4269 non-null   int64
dtypes: int64(9), object(2)
memory usage: 367.0+ KB

In [11]:
# combine all assest columns
X['total_assets_value'] = X['residential_assets_value'] + X['commercial_assets_value'] + X['luxury_assets_value'] + X['bank_asset_value']
X.drop(columns=['residential_assets_value', 'commercial_assets_value', 'luxury_assets_value', 'bank_asset_value'], inplace=True)

X.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,total_assets_value
0,2,Graduate,No,9600000,29900000,12,778,50700000
1,0,Not Graduate,Yes,4100000,12200000,8,417,17000000
2,3,Graduate,No,9100000,29700000,20,506,57700000
3,3,Graduate,No,8200000,30700000,8,467,52700000
4,5,Not Graduate,Yes,9800000,24200000,20,382,55000000

In [12]:
print(X['education'].unique())
print(X['self_employed'].unique())

[' Graduate' ' Not Graduate']
[' No' ' Yes']

In [13]:
# remove blank spaces from the column values
X.education = X.education.str.strip()
X.self_employed = X.self_employed.str.strip()
y = y.str.strip()

In [14]:
# transform to binary
def transform_to_binary(df, columns_to_transform):
    """
    Transfrom specified columns in a DataFrame to binary(0 and 1)

    Args:
        df: The dataframe to modify
        columns_to_transform: A dictionary where keys are column names and values are
                            list of the original categorical values to map to 1.

    Returns:
        Dataframe with modified column.
    """

    for column_name, positive_values in columns_to_transform.items():
        df[column_name] = df[column_name].apply(lambda x:1 if x in positive_values else 0)

    return df

columns_to_transform = {
    'education': ['Graduate'],
    'self_employed': ['Yes']
}

transformed_X = transform_to_binary(X, columns_to_transform)
transformed_X.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,total_assets_value
0,2,1,0,9600000,29900000,12,778,50700000
1,0,0,1,4100000,12200000,8,417,17000000
2,3,1,0,9100000,29700000,20,506,57700000
3,3,1,0,8200000,30700000,8,467,52700000
4,5,0,1,9800000,24200000,20,382,55000000

In [15]:
# log transformation

log_cols = ['income_annum', 'loan_amount', 'total_assets_value']
transformed_X[log_cols] = np.log(transformed_X[log_cols])

transformed_X.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,total_assets_value
0,2,1,0,16.077274,17.213369,12,778,17.741436
1,0,0,1,15.226498,16.316947,8,417,16.648724
2,3,1,0,16.023785,17.206658,20,506,17.870768
3,3,1,0,15.919645,17.239773,8,467,17.780126
4,5,0,1,16.097893,17.001863,20,382,17.822844

In [16]:
y = y.map({'Approved': 1, 'Rejected': 0})
y.head()

0    1
1    0
2    0
3    0
4    0
Name: loan_status, dtype: int64

In [17]:
X.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,total_assets_value
0,2,1,0,16.077274,17.213369,12,778,17.741436
1,0,0,1,15.226498,16.316947,8,417,16.648724
2,3,1,0,16.023785,17.206658,20,506,17.870768
3,3,1,0,15.919645,17.239773,8,467,17.780126
4,5,0,1,16.097893,17.001863,20,382,17.822844

In [18]:
# Build model
from sklearn.linear_model import LogisticRegression

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=18)

log = LogisticRegression()
log.fit(X_train, y_train)

/opt/anaconda3/envs/ML-DL-Learn/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [19]:
y_test_pred = log.predict(X_test)

In [20]:
from sklearn.metrics import accuracy_score, f1_score

acc = accuracy_score(y_test, y_test_pred)
f1 = f1_score(y_test, y_test_pred)

print('Accuracy: ', acc)
print('F1 Score: ', f1)

Accuracy:  0.9133489461358314
F1 Score:  0.9324817518248175

## Saving the model file

### Serialization

In [21]:
import joblib

In [22]:
joblib.dump(log, 'model-log-reg.pkl')

['model-log-reg.pkl']

### Deserialization

In [23]:
final_model = joblib.load('model-log-reg.pkl')

In [24]:
final_model.intercept_, final_model.coef_

(array([-2.72852356]),
 array([[-0.06867379,  0.13065803, -0.37076645, -2.24597099,  2.15764675,
         -0.15402534,  0.02394469, -0.52084273]]))

In [25]:
log.intercept_, log.coef_

(array([-2.72852356]),
 array([[-0.06867379,  0.13065803, -0.37076645, -2.24597099,  2.15764675,
         -0.15402534,  0.02394469, -0.52084273]]))

## gathering info for requirements file

In [26]:
pd.__version__

'2.3.3'

In [27]:
np.__version__

'2.1.3'

In [28]:
joblib.__version__

'1.5.3'

In [31]:
import sklearn
sklearn.__version__

'1.8.0'

In [32]:
import setuptools
setuptools.__version__

'80.10.2'

In [33]:
import scipy
scipy.__version__

'1.16.3'

In [34]:
import wheel
wheel.__version__

'0.46.3'